# Generated by Django 5.1.3 on 2024-12-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_remove_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
